CUDA_SM = 70,"code=sm_70"
VPATH = $(HOME)/GIT/PFiSM/source

HYPRE_DIR    = $(HOME)/hypre/xl_gpu
SUNDIALS_DIR = $(HOME)/sundials/build_xl
SAMRAI_DIR   = $(HOME)/GIT/SAMRAI/build_xl_nohypre

include $(SAMRAI_DIR)/config/Makefile.config

NVCC = nvcc
CXX = mpicxx

INCLUDE_FLAGS = -I$(SAMRAI_DIR)/include -I$(HYPRE_DIR)/include \
            -I$(SUNDIALS_DIR)/include

CXXFLAGS += $(INCLUDE_FLAGS)
NVCCFLAGS = -O0 -g -ccbin=mpixlC -gencode arch=compute_$(CUDA_SM) \
            -expt-extended-lambda -dc --std=c++11 -Xcompiler \
            -Wno-deprecated-register --x cu -Xcompiler "-O2 " \
            -Xcompiler "-fPIC" -DHAVE_CONFIG_H \
            -DHYPRE_TIMING -DHYPRE_FORTRAN \
            -DHYPRE_USE_CUDA \
            $(INCLUDE_FLAGS)

LDLIBS= \
	-L$(HYPRE_DIR)/lib -lHYPRE \
	-L$(SUNDIALS_DIR)/lib -lsundials_cvode \
	-lhdf5 -lm

# how to produce objects from source files
M4DIRS = ${SAMRAI_DIR}/include/SAMRAI/pdat/fortran

%.o:%.C		$(VPATH)/*.C
	$(NVCC) $(NVCCFLAGS) -c $<
FORTCOMM         = $(VPATH)/fortran
%.o:            $(FORTCOMM)/%.m4
	$(M4) -DPDAT_FORTDIR=$(M4DIRS) $(FORTCOMM)/$*.m4 > $*.f
	$(F77) $(FFLAGS) -c $*.f -o $@

TARGET = main
HYPRELINK = libPFiSM_Hypre.so

all: $(TARGET) $(HYPRELINK)
lib: $(HYPRELINK)

OBJS = PfmFACSolver.o PFModel.o main.o 
SAMRAI_OBJS = CellPoissonFACOps.o \
              CellPoissonHypreSolver.o \
              CellPoissonFACSolver.o

F77_OBJS = computeCforPhase.o rhs3d.o

NVCCLINKFLAGS = -ccbin=mpicxx -gencode arch=compute_$(CUDA_SM) \
	-Xcompiler "" \
        -lstdc++ -lm  \
        -L$(OLCF_CUDA_ROOT)/lib64 \
	-lcusparse -lcudart -lcublas -lnvToolsExt

# rules
$(TARGET):	$(OBJS) $(F77_OBJS) $(SAMRAI_OBJS)
	$(NVCC) $(NVCCLINKFLAGS) -o $(TARGET) $(OBJS) $(F77_OBJS) $(SAMRAI_OBJS) \
	$(LIBSAMRAI) $(LDLIBS)

HYPRELINK_OBJS = PFiSM_Hypre.o

$(HYPRELINK):	$(HYPRELINK_OBJS)
	$(NVCC) $(NVCCLINKFLAGS) -DHYPRE_USE_CUDA $(HYPRELINK_OBJS) -o $@ -shared

clean:
	rm -f *.o
	rm -f *.f
	rm -f main
	
