#!/bin/csh
module load hdf5
module load cmake/3.6.1
module load xl

cmake  \
	-DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_CC_COMPILER=mpiCC \
	-DCMAKE_Fortran_COMPILER=f77 \
        -D CMAKE_BUILD_TYPE=Debug \
	-DSAMRAI_DIR=$HOME/GIT/SAMRAI/build_summitdev_xl \
        -DHYPRE_DIR=$HOME/hypre/summitdev_xl_cpu \
        -DSUNDIALS_DIR=$HOME/sundials/build_summitdev_xl \
	../source
