#!/bin/csh
module load hdf5
module load xl
module load cuda
module load cmake

cmake \
	-DCMAKE_CXX_COMPILER=mpiCC \
	-DCMAKE_Fortran_COMPILER=f77 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DPFISM_USE_GPU=ON \
        -DCMAKE_CUDA_FLAGS="-arch=sm_70" \
        -DPFISM_CUDA_ARCHITECTURES="70" \
        -DMPIEXEC_EXECUTABLE="/sw/summit/xalt/1.2.1/bin/jsrun" \
        -DMPIEXEC_NUMPROCS_FLAG="-n" \
        -DMPIEXEC_PREFLAGS="-a1;-c7;-bpacked:2;-g1" \
	-DSAMRAI_DIR=$HOME/SAMRAI/install_nohypre \
        -DHYPRE_DIR=$HOME/hypre/summit_xl_gpu \
        -DSUNDIALS_DIR=$HOME/sundials/sundials-5.0.0_summit_xl \
        ..
