#!/bin/csh
module swap PrgEnv-pgi PrgEnv-gnu
module swap gcc gcc/7.2.0
module load craype-network-gemini
module load cray-mpich
module load cray-netcdf
module load cray-hdf5
module load cmake3/3.9.0

cmake -DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=cc \
	-DCMAKE_Fortran_COMPILER=ftn \
	-DSAMRAI_DIR=$HOME/GIT/SAMRAI/build_titan \
	-DHYPRE_DIR=$HOME/hypre/hypre-2.11.1/src/hypre_gnu \
	-DSUNDIALS_DIR=$HOME/sundials/build_titan \
	-DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF ../source

