#!/bin/csh
module load hdf5
module load xl
module load cmake

cmake \
	-DCMAKE_CXX_COMPILER=mpiCC \
	-DCMAKE_Fortran_COMPILER=f77 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DMPIEXEC_EXECUTABLE="/sw/summit/xalt/1.1.4/bin/jsrun" \
        -DMPIEXEC_NUMPROCS_FLAG="-n" \
        -DMPIEXEC_PREFLAGS="-a1;-c7;-bpacked:2;-g1" \
	-DSAMRAI_DIR=$HOME/GIT/jeanlucf22/SAMRAI/build_summit_xl \
        -DHYPRE_DIR=$HOME/hypre/summit_xl_cpu \
        -DSUNDIALS_DIR=$HOME/sundials/build_summit_xl \
	..
